#!/bin/bash

# this script takes the http port of all followers from the leader
# and requests any given endpoint from all of them

# ----------------- Dependencies -----------------------

jps=$(which jps); grep=$(which grep); cut=$(which cut)
curl=$(which curl); awk=$(which awk); lsof=$(which lsof)
jq=$(which jq); tr=$(which tr)

# ------------------------------------------------------

EP="$1"
[ -z "$1" ] && EP="help"
[ ! -z ${2} ] && EP=$EP"?detail=true"
leader=$(./leader)
CONTEXT="/minka/admin"
SHARDS="$CONTEXT/shards"

CMD="$($curl -s $leader$SHARDS | $jq '.shards[]|(."web-connect"+"#"+.tag)' | $tr -d \")"
declare a=0
declare o="["
for f in ${CMD[@]}; do
	IP=$(echo $f | cut -d# -f1)
	TAG=$(echo $f | cut -d# -f2)
	js=$($curl -s $IP$CONTEXT/$EP | $jq '.' -c)
	js="{\"tag\":\"$TAG\",\"http\":\"$IP\",\"$EP\":$js}"
	[ "$a" == 0 ] && a=1 || o=$o","
	o=$o""$js
done
o=$o"]"

echo -n -e "$o" | $jq -s . 
