#!/bin/bash

# this script finds leader and requests an endpoint

# -------- Dependencies ----------

curl=$(which curl); tee=$(which tee); jq=$(which jq); watch=$(which watch)

# --------------------------------

$watch -n1 -tc "./follower-request $1 $2 | $jq . -C"
