#!/bin/bash

# this script takes the http port of all followers from the leader
# and requests any given endpoint from all of them

# ----------------- Dependencies -----------------------

jps=$(which jps); grep=$(which grep); cut=$(which cut)
curl=$(which curl); awk=$(which awk); lsof=$(which lsof)
jq=$(which jq); tr=$(which tr)

# ------------------------------------------------------

EP="$1"
if [ ! -z ${2} ]; then
	EP=$EP"?detail=true"
fi
leader=$(./leader)
CONTEXT="/minka/admin"
SHARDS="$CONTEXT/shards"

CMD="$($curl -s $(./leader)$SHARDS | $jq '.shards[].id["web-host-port"]' | $tr -d \")"
for f in ${CMD[@]}; do
	x=$(for i in {1..30}; do h=$h"-"; done; echo $h)
	echo "$x $f $x"
	$curl -s $f$CONTEXT/$EP | $jq
done
