#!/bin/bash

# this script takes the http port of all followers from the leader
# and requests any given endpoint from all of them

# ----------------- Dependencies -----------------------

jps=$(which jps); grep=$(which grep); cut=$(which cut)
curl=$(which curl); awk=$(which awk); lsof=$(which lsof)
jq=$(which jq); tr=$(which tr)

# ------------------------------------------------------

EP="$1"
[ ! -z ${2} ] && EP=$EP"?detail=true"
leader=$(./leader)
CONTEXT="/minka/admin"
SHARDS="$CONTEXT/shards"

CMD="$($curl -s $(./leader)$SHARDS | $jq '.shards[].id["web-host-port"]' | $tr -d \")"
declare a=0
declare o="["
for f in ${CMD[@]}; do
	js=$($curl -s $f$CONTEXT/$EP | $jq '.' -c)
	js="{\"follower\":\"$f\",\"$EP\":$js}"
	[ "$a" == 0 ] && a=1 || o=$o","
	o=$o""$js
done
o=$o"]"

echo -n -e $o
