#!/bin/bash
# discover rest port of the leader shard
for PID in `$(which jps) -mlv | $(which grep) minka | $(which cut) -d' ' -f1`; do
	LOCAL_ADDRESS=$($(which netstat) -pltn 2>/dev/null | $(which grep) $PID | $(which awk) '{print $4}'); 
	for HOSTPORT in ${LOCAL_ADDRESS[@]}; do
		LEADER="$(which curl) $HOSTPORT/minka/admin/shards -XGET -sn "
		LEADER=$($LEADER | $(which jq) '.leaderShardId."web-host-port" ' | $(which tr) -d '\" ')
		[ "$?" == 0 ] && echo $LEADER && exit 0
	done
done
echo "no leader found!"
exit 1

