#!/bin/bash
[ -z "$1" ] || [ -z "$2" ] || [ -z "$3" ] && echo "Usage: ./newbatt {pallet-id} {duty-initial-id} {duty-final-id}" && exit 1
for i in $(seq $2 $3); do 
	./newduty $1 $1$i 99$i | grep message & sleep 0.2; 
done
