#!/bin/bash

# this script finds leader and requests an endpoint

# -------- Dependencies ----------

curl=$(which curl); tee=$(which tee); jq=$(which jq); watch=$(which watch)

# --------------------------------

EP="/minka/admin/$1"
if [ ! -z ${2} ]; then
	EP=$EP"?detail=true"
fi
cmd="echo ========== $1 ==========; $curl -s \$(./leader)$EP | $tee ./last-$1 | $jq . -C"
$watch -n1 -tc $cmd
