#!/bin/bash
[ -z "$1" ] || [ -z "$2" ] || [ -z "$3" ] && \
	echo "Usage: ./rembatt {pallet-id} {duty-initial-id} {duty-final-id} [consistency-level]" && exit 1

PID="$1"
ID="$2"
CL="$3"

leader=$(./leader)
CONTEXT="/minka/admin"
DUTIES="$CONTEXT/crud/duty"
curl=$(which curl)
x=""
for did in $(seq $2 $3); do 
	x="$x $curl -XDELETE -s $leader$DUTIES/$PID/$PID$did?cl=$CL | jq . &"
done
echo "Requesting..."
eval $x
