#!/bin/bash

# ----------------- Dependencies -----------------------

jps=$(which jps); grep=$(which grep); cut=$(which cut)
curl=$(which curl); awk=$(which awk); lsof=$(which lsof)
jq=$(which jq); tr=$(which tr)

# ------------------------------------------------------

PID="$1"
ID="$2"

if [ ! -n "$2" ] || [ ! -n "$1" ]; then
	printf "\nUsage: ./remduty {pallet-id} {duty-id}\n\n"
	exit
fi


leader=$(./leader)
CONTEXT="/minka/admin"
DUTIES="$CONTEXT/crud/duty"

$curl -XDELETE -s $leader$DUTIES"/$PID/$ID" | $jq '.'

