#!/bin/bash

# ----------------- Dependencies -----------------------

jps=$(which jps); grep=$(which grep); cut=$(which cut)
curl=$(which curl); awk=$(which awk); lsof=$(which lsof)
jq=$(which jq); tr=$(which tr)

# ------------------------------------------------------

[ -z "$1" ] || [ -z "$2" ] && echo "Usage: ./remduty {pallet-id} {duty-id} " && exit 1

PID="$1"
ID="$2"

leader=$(./leader)
CONTEXT="/minka/admin"
DUTIES="$CONTEXT/crud/duty"

$curl -XDELETE -s $leader$DUTIES"/$PID/$ID" | $jq '.'

