#!/bin/bash

# this script finds leader and requests an endpoint

# -------- Dependencies ----------

curl=$(which curl); tee=$(which tee); jq=$(which jq); watch=$(which watch)

# --------------------------------


[ -z "$1" ] && echo -e "\nUsage: ./watchfoll [help]\n" && exit 1
$watch -n1 -tc "echo \" _____________  $1 _____________\"; ./askfoll $1 $2 | $jq . -C"
